export const LOGIN_REQUEST = 'loginPage/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'loginPage/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'loginPage/LOGIN_FAILURE';

export const TOKEN = 'TOKEN';
export const USERNAME = 'USERNAME';

export const LOGIN_FROM_STORAGE_REQUEST = 'loginPage/LOGIN_FROM_STORAGE_REQUEST';
export const LOGIN_FROM_STORAGE_SUCCESS = 'loginPage/LOGIN_FROM_STORAGE_SUCCESS';
export const LOGIN_FROM_STORAGE_FAILURE = 'loginPage/LOGIN_FROM_STORAGE_FAILURE';

export const LOGOUT_FROM_STORAGE_REQUEST = 'loginPage/LOGOUT_FROM_STORAGE_REQUEST';
export const LOGOUT_FROM_STORAGE_SUCCESS = 'loginPage/LOGOUT_FROM_STORAGE_SUCCESS';
export const LOGOUT_FROM_STORAGE_FAILURE = 'loginPage/LOGOUT_FROM_STORAGE_FAILURE';